export const reviews = [
  {
    username: "Krzysztof Szulc",
    avatarSrc: "/reviews/krzysztof-szulc.png",
    timeAgo: "5 lat temu",
    rating: 5.0,
    body: "Jestem bardzo zadowolony z Ich usług. Byłem 3 razy i za każdym razem: umówienie na konkretną godzinę, wycena i naprawa!! Polecam!!",
  },
  {
    username: "Grzegorz K",
    avatarSrc: "/reviews/grzegorz-k.png",
    timeAgo: "1 rok temu",
    rating: 5.0,
    body: "Wpadłem tam bez zamówionej wizyty więc zakładałem że się nie da. Myliłem się na moje szczęście. Szybka i sprawna ekspertyza problemu bardzo profesjonalne podejście do klienta",
  },
  {
    username: "Ireneusz Wrzeszcz",
    avatarSrc: "/reviews/ireneusz-wrzeszcz.png",
    timeAgo: "2 lata temu",
    rating: 5.0,
    body: "Miła i profesjonalna obsługa, usługi wykonane szybko i solidnie. Godne polecenia.",
  },
  {
    username: "zbigniew",
    avatarSrc: "/reviews/zbigniew.png",
    timeAgo: "1 rok temu",
    rating: 5.0,
    body: "Zakład świadczący usługi napraw samochodów godny zaufania.Tu Cię nie oszukają!!! Pozdrawiam stały klient.",
  },
  {
    username: "Kacper Bysko",
    avatarSrc: "/reviews/kacper-bysko.png",
    timeAgo: "5 lat temu",
    rating: 5.0,
    body: "Oby więcej takich warsztatów było. Konkretnie i na temat. Wczoraj od dałem auto a dzisiaj go już odebrałem 😀",
  },
  {
    username: "Jacek Zingler",
    avatarSrc: "/reviews/jacek-zingler.png",
    timeAgo: "2 lata temu",
    rating: 5.0,
    body: "Elektromechanik -fachowiec! Polecam 100%!",
  },
  {
    username: "Mateusz Solich",
    avatarSrc: "/reviews/mateusz-solich.png",
    timeAgo: "6 lat temu",
    rating: 4.0,
    body: "Uczciwa firma, dobrze i dużo robią, ceny przeciętne.",
  },
  {
    username: "Barbara Basia",
    avatarSrc: "/reviews/barbara-basia.png",
    timeAgo: "1 rok temu",
    rating: 5.0,
    body: "Polecam,miła sympatycza obsługa,właściciele są konkretni i dokładni,samochód był naprawiony punktualnie. Podziwiam właścicieli.😀",
  },
  {
    username: "ru kaj",
    avatarSrc: "/reviews/ru-kaj.png",
    timeAgo: "3 lata temu",
    rating: 5.0,
    body: "Uczciwa Bardzo profesjonalnie sprawnie i w miarę tanio, dobrze i dużo robią, ceny przeciętne.",
  },
];
